PFM dashboard screen, Category scree, transaction history screen
101digital/account-origination-component pull request #28
Opened 2023-03-22 12:46 UTC by Salman1019864

### Why

Please give a short description why these code changes are being made, by replacing this line.

Link to Jira ticket: <place here>

https://101digital.atlassian.net/browse/ADBP-2100
https://101digital.atlassian.net/browse/ADBP-2099
https://101digital.atlassian.net/browse/ADBP-2098

### ToDo

- [ ]
- [ ]
- [ ]

If this is a `Draft:` or `WIP:` PR, please describe still needed actions, else delete section

2023-03-23 01:54 UTC, sharmal33 requested changes

2023-03-23 01:54 UTC, sharmal33 commented on src/components/adb-personal-financial-management-dashboard/index.tsx
why this value are hardcoded.

plz use theme colors

2023-03-23 01:54 UTC, sharmal33 commented on src/components/adb-pfa-category-deep-dive/index.tsx
plz use theme colors

2023-03-23 01:54 UTC, sharmal33 commented on src/components/adb-pfa-transaction-history/index.tsx
plz move all static content into translations file

2023-03-27 02:30 UTC, sharmal33 requested changes

2023-03-27 02:30 UTC, sharmal33 commented on src/components/adb-pfa-category-deep-dive/index.tsx
> +            data={['Food', 'Utilities', 'Transfer', 'Others' ]}
plz move these to const file -> src/helpers/screen-utils

2023-03-27 02:30 UTC, sharmal33 commented on src/components/adb-pfa-category-deep-dive/index.tsx
move all static content to translations file

2023-03-27 09:33 UTC, Salman1019864 commented
all static content to translations file

this pr also have some changes after text is moved 
PR
https://github.com/101digital/aeon-app/pull/105

2023-03-31 11:26 UTC, merged