Onboarding - [FE] View funds transfer verification (FTV) instructions
101digital/account-origination-component pull request #33
Opened 2023-03-24 12:56 UTC by jaypoojara101digital

Onboarding - [FE] View funds transfer verification (FTV) instructions

Link to Jira ticket: https://101digital.atlassian.net/browse/ADBP-1938

2023-03-28 00:23 UTC, sharmal33 requested changes

2023-03-28 00:23 UTC, sharmal33 commented on src/components/adb-fund-transfer-verify-popup/index.tsx
> +import { ForwardIcon } from 'account-origination-component/src/assets/icons/forward-arrow.icon';
just import icon folder
import { ImageIcon,DollarIcon ,ForwardIcon} from 'account-origination-component/src/assets/icons';

2023-03-28 00:23 UTC, sharmal33 commented on src/components/adb-fund-transfer-verify-popup/index.tsx
> +            <View style={{ width: '80%' }}>
why inline style

2023-03-28 10:12 UTC, jaypoojara101digital commented on src/components/adb-member-plus-dashboard/index.tsx
> -  }
It was already there - I have amended the } bracket - but I will still change it.

2023-03-31 04:29 UTC, sharmal33 approved these changes

2023-03-31 05:28 UTC, merged