IAM - [FE] Account lockout
101digital/account-origination-component pull request #34
Opened 2023-03-24 14:24 UTC by jaypoojara101digital

IAM - [FE] Account lockout

Link to Jira ticket: https://acsdigital.atlassian.net/browse/APB-729

2023-03-27 02:27 UTC, sharmal33 requested changes

2023-03-27 02:27 UTC, sharmal33 commented on src/components/adb-login-with-password/index.tsx
> +        if (isSuccess?.error?.code === 'PASSWORD_LOCKED_OUT') {
plz move this to const file

2023-03-27 05:11 UTC, jaypoojara101digital commented on src/components/adb-login-with-password/index.tsx
> +        if (isSuccess?.error?.code === 'PASSWORD_LOCKED_OUT') {
Can't move. It's storing api response to it.

2023-03-28 00:19 UTC, sharmal33 requested changes

2023-03-28 05:15 UTC, jaypoojara101digital commented on src/components/adb-login-with-password/index.tsx
> +        if (isSuccess?.error?.code === 'PASSWORD_LOCKED_OUT') {
HI @sharmal33, sorry I misunderstood the comment. I will push it a few mins.

2023-03-31 04:26 UTC, sharmal33 approved these changes

2023-03-31 05:34 UTC, merged