Feature/adbp 1480
101digital/account-origination-component pull request #49
Opened 2023-04-03 08:47 UTC by muh-techie

### Why

Please give a short description why these code changes are being made, by replacing this line.

Link to Jira ticket: <place here>

### ToDo

- [ ]
- [ ]
- [ ]

If this is a `Draft:` or `WIP:` PR, please describe still needed actions, else delete section

2023-04-03 10:04 UTC, sharmal33 requested changes

2023-04-03 10:04 UTC, sharmal33 commented on src/components/adb-account-openning/index.tsx
> +              By continuing, I agree and comply with {'{ADB}’s'}{' '}
move this to translation file

2023-04-03 10:04 UTC, sharmal33 commented on src/components/adb-account-openning/index.tsx
> +                  privacy policy
plz move all string to translation file

2023-04-03 10:04 UTC, sharmal33 commented on src/context/onboarding-context.ts
> +      console.log("getPIN -> value", value);
remove logs

2023-04-03 10:04 UTC, sharmal33 commented on src/service/onboarding-service.ts
> +      });
why values are hardcoded

2023-04-04 03:02 UTC, muh-techie commented on src/context/onboarding-context.ts
> +      console.log("getPIN -> value", value);
@sharmal33 its a old code but I have remove it

2023-04-04 03:05 UTC, muh-techie commented on src/service/onboarding-service.ts
> +      });
its need to be hardcode as Tung mention

![image](https://user-images.githubusercontent.com/126800866/229676352-44659431-629e-4569-8baf-5c0aa3d11c6c.png)

2023-04-04 03:06 UTC, sharmal33 approved these changes

2023-04-04 03:14 UTC, merged