APB-850 Onboarding - [FE] Resume Savings Account-i application
101digital/account-origination-component pull request #58
Opened 2023-04-05 13:51 UTC by jaypoojara101digital

APB-850 Onboarding - [FE] Resume Savings Account-i application

Link to Jira ticket: https://acsdigital.atlassian.net/browse/APB-850

2023-04-06 00:14 UTC, sharmal33 requested changes

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-lite-home-screen/components/functionality-list.tsx
> +      style={{ marginVertical: 20 }}
inline style

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-lite-home-screen/components/product-carousel-view.tsx
> +            <View style={{ alignItems: 'center', position: 'absolute', top: 10, left: 10, width: 111, paddingVertical: 10, justifyContent: 'center', backgroundColor: "#8E8E93", borderRadius: 40 }}>
inline style

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-lite-home-screen/components/product-carousel-view.tsx
> +            <View style={{ alignSelf: 'flex-end', position: 'absolute', bottom: 5, left: 12 }}>
inline style

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-lite-home-screen/index.tsx
> +          <ImageIcon size={30} color={'#FFFFFF'} />
use theme colors

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-lite-home-screen/index.tsx
> +            <View style={{ width: '80%' }}>
inline style

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-member-plus-dashboard/index.tsx
> +  openSavingAccountContainer: { height: 76, borderRadius: 12, width: '100%', padding: 10, backgroundColor: '#8E8E93', flexDirection: 'row', alignItems: 'center', marginVertical: 10, justifyContent: '
use theme colors

2023-04-06 00:14 UTC, sharmal33 commented on src/components/adb-member-plus-dashboard/index.tsx
> +    color: '#FCFCFC', fontSize: 10, fontFamily: fonts.regular
use theme colors

2023-04-06 04:55 UTC, jaypoojara101digital commented on src/components/adb-lite-home-screen/components/functionality-list.tsx
> +      style={{ marginVertical: 20 }}
Resolved

2023-04-06 04:55 UTC, jaypoojara101digital commented on src/components/adb-lite-home-screen/components/product-carousel-view.tsx
> +            <View style={{ alignItems: 'center', position: 'absolute', top: 10, left: 10, width: 111, paddingVertical: 10, justifyContent: 'center', backgroundColor: "#8E8E93", borderRadius: 40 }}>
Resolved

2023-04-06 04:57 UTC, jaypoojara101digital commented on src/components/adb-member-plus-dashboard/index.tsx
> +  openSavingAccountContainer: { height: 76, borderRadius: 12, width: '100%', padding: 10, backgroundColor: '#8E8E93', flexDirection: 'row', alignItems: 'center', marginVertical: 10, justifyContent: '
Removed code it's not required here now.

2023-04-06 04:57 UTC, jaypoojara101digital commented on src/components/adb-member-plus-dashboard/index.tsx
> +    color: '#FCFCFC', fontSize: 10, fontFamily: fonts.regular
Removed code it's not required here now.

2023-04-10 07:05 UTC, sharmal33 requested changes

2023-04-10 07:05 UTC, sharmal33 commented on src/components/adb-lite-home-screen/index.tsx
> +            <Text style={styles.label10}>{`{200 pts} will be expired on {Mar 2023}`}</Text>
why this one is hardcoded ?

2023-04-10 07:05 UTC, sharmal33 commented on src/components/adb-lite-home-screen/index.tsx
> +              <Text style={styles.label}>{i18n.t('lite_home.expiry') ?? 'Expiry'} 10/26</Text>
hardcoded

2023-04-10 09:16 UTC, jaypoojara101digital commented on src/components/adb-lite-home-screen/index.tsx
> +            <Text style={styles.label10}>{`{200 pts} will be expired on {Mar 2023}`}</Text>
This data should be coming from the api back end so. I have just added screen design part. @sharmal33 for showing the resume application popup on that screen.

2023-04-10 09:16 UTC, jaypoojara101digital commented on src/components/adb-lite-home-screen/index.tsx
> +              <Text style={styles.label}>{i18n.t('lite_home.expiry') ?? 'Expiry'} 10/26</Text>
This data should be coming from the api back end so. I have just added screen design part. @sharmal33 for showing the resume application popup on that screen.

2023-04-11 00:57 UTC, merged