uat android fixes
101digital/account-origination-component pull request #72
Opened 2023-04-11 07:45 UTC by Salman1019864

UAT Android App fixes

2023-04-11 08:06 UTC, sharmal33 requested changes

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-kyc-openning/index.tsx
>      backgroundColor: '#F5F5F5',
use theme colors

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-opening-purpose/index.tsx
>            ? listBSData.filter((c) => c.value !== 'Malaysia')
why 'Malaysia' is hardcoded in here ?
get it from utils file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-opening-purpose/index.tsx
>                          console.log('listTaxes -> item', t);
remove logs

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-openning/index.tsx
> +            <Text style={styles.policyTextLinks} onPress = {handleOnPolicyPress}>{'Read more.'}</Text>
get it from translations file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-term-conditions/index.tsx
> +    console.log('onViewPrivacyAndPolicy => privacyLink', privacyLink);
remove logs

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-term-conditions/index.tsx
> +    setDocumentTitle(`PIDM's brochure`);
get it from translation file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-term-conditions/index.tsx
> +              Malaysia in the same name (only applicable for Malaysian citizens)
get it from translation file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-term-conditions/index.tsx
>                {`I understand that this account is protected by PIDM up to RM250,000 for each depositor and I have received a copy of `}
get all static string from translations file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-account-term-conditions/index.tsx
>                {`By continuing, I agree and comply with {ADB}’s \nand AEON membership’s`}
get this from translation file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +    console.log('selectedData',metadata?.fields,name)
remove log

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +      console.log('getOccupationList',response)
remove log

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +      console.log('error12',error)
remove log

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +  console.log('bsData',bsData)
remove log

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +          console.log('errors1', errors);
remove log

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +            prefixText={'RM'}
get it from translation file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-employment-details/index.tsx
> +                  title={bsData.name  === 'employmentSector'? "Employment Sector" : bsData.title}
get it from translation file

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-enable-push-notification/index.tsx
>      backgroundColor: '#F5F5F5',
plz use theme colors

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-enable-push-notification/index.tsx
>      backgroundColor: '#D9D9D9',
use theme colors

2023-04-11 08:06 UTC, sharmal33 commented on src/components/adb-personal-details-review/index.tsx
> +      : bsData.items.filter((i: BSOption) => i.value !== "Not Applicable")
get it from translation file

2023-04-13 07:19 UTC, usamabutt101 approved these changes

2023-04-13 07:28 UTC, merged